/**
 *
 */
package com.snehee.ganpati.enums;

/**
 * @author Bapat_G
 *
 */
public enum Reason {
	CUSTOMER_CHOSE_DIFFERENT_IDOL_TYPE,CUSTOMER_CHOSE_ANOTHER_IDOL_OF_SAME_TYPE,SOYAR_IN_FAMILY, SUTAK_IN_FAMILY,
	CUSTOMER_FORGOT_TO_COLLECT_IDOL,CUSTOMER_REFUSED_TO_BUY_IDOL,CUSTOMER_CANCELLED_BOOKING,IDOL_DAMAGED,PROBLEM_AT_CUSTOMERS_END,OTHER
}
